#!/bin/sh

me=bootstrap

git submodule init || {
    echo "$me: cannot init submodule"
    exit 1
}

git submodule update || {
    echo "$me: cannot update submodule"
    exit 1
}

python build-aux/virtualenv/virtualenv.py build-aux/environment || {
    echo "$me: cannot build the virtual environment"
    exit 1
}

source build-aux/environment/bin/activate || {
    echo "$me: cannot activate the virtual environment"
    exit 1
}

python build-aux/django/setup.py install || {
    echo "$me: cannot install django into the environment"
    exit 1
}

exit 0
