#!/bin/bash

me=site-db-init

source extra/environment/bin/activate || {
    echo "$me: cannot activate the virtual environment"
    exit 1
}

(cd project && rm -f database.db)       || exit 1
(cd project && python manage.py syncdb) || exit 1

exit 0
