#!/bin/bash

me=site-test

source extra/environment/bin/activate || {
    echo "$me: cannot activate the environment"
    exit 1
}

(cd project && python manage.py runserver) || {
    echo "$me: cannot run the server"
    exit 1
}

exit 0
