#!/bin/bash

me=site-manage

source extra/environment/bin/activate || {
    echo "$me: cannot activate the environment"
    exit 1
}

(cd project && python manage.py $@) || {
    echo "$me: cannot manage $1"
    exit 1
}

exit 0
